<?php

     /**
     * Implementation of hook_menu()
     */
    function mypage_menu() {

        $items['simple_page'] = array(
            'title' => 'Simple page',
            'page callback' => 'simple_page_content',
            'access callback' => TRUE,
            'menu_name' => 'main-menu',
            'file' => 'pages.php',
            'options' => array('attributes' => array('class' => array('test-class'))),
        );

        $items['simple_page/main-tab'] = array(
            'title' => 'Simple page (main tab)',
            'page callback' => 'simple_page_content',
            'access callback' => TRUE,
            'menu_name' => 'main-menu',
            'type' => MENU_DEFAULT_LOCAL_TASK,
            'file' => 'pages.php',
        );

        $items['simple_page/sub-tab'] = array(
            'title' => 'Simple page (sub tab)',
            'page callback' => 'simple_page_content',
            'access callback' => TRUE,
            'menu_name' => 'main-menu',
            'type' => MENU_LOCAL_TASK,
            'file' => 'pages.php',
        );

        $items['simple_page/sub-tab2'] = array(
            'title' => 'Simple page (local action)',
            'page callback' => 'simple_page_content',
            'access callback' => TRUE,
            'menu_name' => 'main-menu',
            'type' => MENU_LOCAL_ACTION,
            'file' => 'pages.php',
        );

        $items['admin/settings/onthisdate'] = array(
            'title' => 'My page module settings',
            'description' => 'About your mypage module settings page',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('mypage_admin'),
            'access arguments' => array('administer mymodule settings'),
            'type' => MENU_NORMAL_ITEM,
        );

        return $items;
    }

    /**
    * Implementation of mypage_admin()
    */
    function mypage_admin() {
        $form = array();
        $form['onthisdate_maxdisp'] = array(
          '#type' => 'textfield',
          '#title' => t('Maximum number of links'),
          '#default_value' => variable_get('onthisdate_maxdisp', 3),
          '#size' => 2,
          '#maxlength' => 2,
          '#description' => t("Maximum number of links to display in the block."),
          '#required' => TRUE,
        );

        return system_settings_form($form);
    }
